env:
  browser: true
  es2022: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - plugin:jest-dom/recommended
parser: '@babel/eslint-parser'
plugins:
  - '@babel'
  - jest
  - react
  - react-hooks
  - testing-library
settings:
  react:
    version: detect
overrides:
  - files:
      - '**/*.mjs'
    parserOptions:
      babelOptions:
        parserOpts:
          plugins: ['importAssertions']
  - files:
      - '**/__tests__/**/*.[jt]s?(x)'
      - '**/?(*.)+(spec|test).[jt]s?(x)'
    extends:
      - 'plugin:testing-library/react'
  - files:
      - '**/*.ts?(x)'
    parser: '@typescript-eslint/parser'
    parserOptions:
      tsconfigRootDir: .
      project: ['./tsconfig.json']
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    rules:
      '@typescript-eslint/no-unused-vars':
        - error
        - varsIgnorePattern: '^_'
          argsIgnorePattern: '^_'
      # For compat with jest: https://typescript-eslint.io/rules/unbound-method/
      '@typescript-eslint/unbound-method': 'off'
      'jest/unbound-method': 'error'
