import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider, ErrorBoundary } from '@rollbar/react';

const inter = Inter({ subsets: ['latin'] });

const rollbarConfig = {
  accessToken: process.env.NEXT_PUBLIC_ROLLBAR_TOKEN,
  hostSafeList: ['localhost:3000', 'localhost:4000'],
  captureUncaught: true,
  captureUnhandledRejections: true,
  payload: {
    environment: 'development',
    client: {
      javascript: {
        code_version: '1.0.0',
        source_map_enabled: true,
      },
    },
  },
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider config={rollbarConfig}>
          <ErrorBoundary
            level="critical"
            errorMessage="example error boundary message"
            fallbackUI={() => (
              <p style={{ color: 'red' }}>Oops, there was an error.</p>
            )}
            extra={{ more: 'data' }}
            callback={() => console.log('an exception was sent to rollbar')}
          >
            {children}
          </ErrorBoundary>
        </Provider>
      </body>
    </html>
  );
}
